import streamlit as st
import google.generativeai as genai
import os
from dotenv import load_dotenv
load_dotenv()
from PIL import Image

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

#backend setup

def get_gemini_response(input_prompt, image):
    model = genai.GenerativeModel('gemini-1.5-flash') #calling the model
    response = model.generate_content([input_prompt, image[0]])
    return response.text

def input_image_setup(uploaded_file):
    #check if a file has been uploaded
    if uploaded_file is not None:
        #read the file into bytes
        bytes_data = uploaded_file.getvalue()

        image_parts = [
            {
                "mime_type":uploaded_file.type,
                "data": bytes_data
            }
        ]
        return image_parts
    else:
        raise FileNotFoundError("No File Uploaded")

#initializing streamlit app ~ front end setup

st.set_page_config(page_title = "RadiX")

st.header("Radix - AI Enhanced Medical Image (X-Ray) Analysis")
uploaded_file = st.file_uploader("Upload the softcopy of the X-Ray image in JPG, JPEG or PNG Format", type = ["jpg", "jpeg", "png"])
image = ""

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image.", use_column_width = 250)

submit = st.button("Generate Report")

input_prompt = """


You are an expert in analyzing soft copies of X-ray images.

The radiologist will upload X-ray image in JPG, JPEG, or PNG format. Your task is to analyze the image carefully and extract the following detailed information:

1. Is there any anomaly in the image?
2. What is the detected anomaly?
3. Where is it located?
4. How severe is the anomaly?
5. What is the size of the anomaly?

The information should be presented in the following format:

Anomaly Detected? (Specify YES if there's any anomaly else NO)

Detected Anomaly: (name of the anomaly)Please describe this anomaly.

Location of the Anomaly: (specify location)

Size: Provide information about the bone density, length of crack, dislocation level, etc., in a manner that is easily understood by a doctor.

Severity: (Low, Intermediate, High, etc.)Provide a detailed explanation of the severity.

Do not provide a diagnostic solution. Instead, focus on analyzing and presenting the information based on the topics outlined above.

Please display the information in a well-defined tabular format with clearly organized rows and columns, as follows:

| Anomaly Detected | (Yes/No) |
| ---------------- | -------- |
| Location | (Location name) |
| Size | (Size Value) |
| Severity | (Severity State) |
| Infections | (Signs of infections) |
| Tumors | (Look for the presence of Tumors) |
| Cogenital Conditions | (Identify structural abnormalities present from birth) |
| Foreign Object | (Look for presence of foreign objects that may accidently ingested or inserted) |
| Swelling | (Detect thee signs of soft tissue swelling or inflammation) |

Also provide a summary of the above the information. Don't provide any diagnositic solution. 
It should be for about 50-100 Words. Don't produce any grametical errors. Include the appropriate
Medical terms then and there. This is for the doctor. Not for any customer/patient

Please ensure a well-defined and organized arrangement of the generated information.

Do not provide an any diagnostic solution. Give me the analysis of it. That's it

Display the following as well: (This should be displayed at the end of the above table)
'The above report is generated by the RaDiX' in a bold manner. This should be highlighted as well

"""
if submit:
    image_data = input_image_setup(uploaded_file)
    response = get_gemini_response(input_prompt, image_data)

    st.header("Medical Report")
    st.write(response)

